version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - "package.json"
    - "nuxt.config.js"
    - ".nuxt/**/*"
    - "static/**/*"
    - ".platform/**/*"
    - ".ebextensions/**/*"